
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.util.Timer; 
import java.util.TimerTask; 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author surin
 */
public class NewJFrame3 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame3
     */
    public NewJFrame3() {
        initComponents();
    }
     public NewJFrame3(String dname1,int fare1)
    {
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cabservice","root","");
            String sql = "Select * from driverdata where Name=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, dname1);
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                dname.setText(dname1);
                dcar.setText(rs.getString("Car"));
                dplate.setText(rs.getString("Numberplate"));
                drating.setText(Integer.toString(rs.getInt("Rating")));
                dfare.setText(Integer.toString(fare1));
                int k=fare1/30;
                k=k*20;
                duration.setText(Integer.toString(k)+" Seconds");
            }
            
            con.close();
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        int t=fare1/30;
        t=20*t*1000;
        Timer timer = new Timer(); 
        TimerTask task = new Helper(dname1); 
          
        timer.schedule(task,t); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dplate = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        drating = new javax.swing.JLabel();
        dcar = new javax.swing.JLabel();
        dfare = new javax.swing.JLabel();
        dname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\vansh\\Downloads\\driver.jpg")); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Driver Details");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 408, 550);

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Car Number Plate");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(430, 150, 140, 50);

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Estimated Duration");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(430, 220, 150, 50);

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Car Model");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(430, 350, 100, 50);

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Driver Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(430, 60, 100, 50);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Estimated Fare");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(430, 420, 110, 50);

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Rating");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(430, 290, 100, 50);

        dplate.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dplate.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(dplate);
        dplate.setBounds(580, 150, 190, 50);

        duration.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        duration.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(duration);
        duration.setBounds(580, 220, 190, 50);

        drating.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        drating.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(drating);
        drating.setBounds(580, 290, 190, 50);

        dcar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dcar.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(dcar);
        dcar.setBounds(580, 350, 190, 50);

        dfare.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dfare.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(dfare);
        dfare.setBounds(580, 420, 190, 50);

        dname.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        dname.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(dname);
        dname.setBounds(580, 60, 190, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dcar;
    private javax.swing.JLabel dfare;
    private javax.swing.JLabel dname;
    private javax.swing.JLabel dplate;
    private javax.swing.JLabel drating;
    private javax.swing.JLabel duration;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
class Helper extends TimerTask 
{ 
    public  static String dname2;
    public Helper(String temp)
    {
        dname2=temp;
    }
    public void run() 
    { 
         try
            {
                Class.forName("com.mysql.jdbc.Driver");
            Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/cabservice","root","");
            
            String query;
             query = "UPDATE driverdata SET Status=? where Name=?";
            PreparedStatement pst1 = con1.prepareStatement(query);
            pst1.setString(2, dname2);
            pst1.setString(1, "FREE");
            pst1.executeUpdate();
            con1.close();
            System.exit(0);
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,e);
            }
    } 
}
